DATABASE_USERNAME: "postgres"
DATABASE_PASSWORD: "postgres"
DATABASE_HOST: "localhost"

DATABASE_NAME: "engineer_ai_development"
development:
  DATABASE_NAME: "engineer_ai_development"

test:
  DATABASE_NAME: "engineer_ai_test"
